mpnn_dir = '../ProteinMPNN'
dir_out_rosetta = "../Rosetta_Design_VR4/"

seq_wt = "MAADGYLPDWLEDNLSEGIREWWALKPGAPQPKANQQHQDNARGLVLPGYKYLGPGNGLDKGEPVNAADAAALEHDKAYDQQLKAGDNPYLKYNHADAEFQERLKEDTSFGGNLGRAVFQAKKRLLEPLGLVEEAAKTAPGKKRPVEQSPQEPDSSAGIGKSGAQPAKKRLNFGQTGDTESVPDPQPIGEPPAAPSGVGSLTMASGGGAPVADNNEGADGVGSSSGNWHCDSQWLGDRVITTSTRTWALPTYNNHLYKQISNSTSGGSSNDNAYFGYSTPWGYFDFNRFHCHFSPRDWQRLINNNWGFRPKRLNFKLFNIQVKEVTDNNGVKTIANNLTSTVQVFTDSDYQLPYVLGSAHEGCLPPFPADVFMIPQYGYLTLNDGSQAVGRSSFYCLEYFPSQMLRTGNNFQFSYEFENVPFHSSYAHSQSLDRLMNPLIDQYLYYLSKTINGSGQNQQTLKFSVAGPSNMAVQGRNYIPGPSYRQQRVSTTVTQNNNSEFAWPGASSWALNGRNSLMNPGPAMASHKEGEDRFFPLSGSLIFGKQGTGRDNVDADKVMITNEEEIKTTNPVATESYGQVATNHQSAQAQAQTGWVQNQGILPGMVWQDRDVYLQGPIWAKIPHTDGNFHPSPLMGGFGMKHPPPQILIKNTPVPADPPTAFNKDKLNSFITQYSTGQVSVEIEWELQKENSKRWNPEIQYTSNYYKSNNVEFAVNTEGVYSEPRPIGTRYLTRNL"
motifs = {
    "4um9":"GRGDLGRL", 
    "5ffo":"RRGDLATI", 
    "5nem":"VRGDLQVL"
}

selected_seqs = {
    "4um9": ["KEGRGDLGRLGE", "APGRGDLGRLGQ", "DEGRGDLGRLKG", "SEGRGDLGRLTG", "AEGRGDLGRLGL"], 
    "5ffo": ["VERRGDLATIGQ", "VDRRGDLATIGQ", "IPRRGDLATIGE", "DERRGDLATIGF", "QDRRGDLATIGI"], 
    "5nem": ["DDVRGDLQVLPN", "TPVRGDLQVLGG", "IEVRGDLQVLAG", "APVRGDLQVLGR", "EEVRGDLQVLGL"],
}
VR4_toreplace = "NGSGQNQ"
VR = VR4_toreplace